### ISSUE TITLE
Transfer maintenance rights to The Foreman

### ISSUE THREAD

**Issue by sandfoxme** [theforeman/journald-logger#4]
* [x] Transfer GitHub repo
* [x] Transfer Rubygems release rights

**Comment by GregSutcliffe** [comment]
Hi @sandfoxme, I can help with the repo transfer. I'm sending you a org invite, once you've accepted you should be able to transfer the repo to the "theforeman" namespace. I can restore admin privs for you and @lzap after that.

**Comment by GregSutcliffe** [comment]
Could you also add "theforeman.rubygems@gmail.com" as an author on the respective rubygems please?

**Comment by sandfoxme** [comment]
done

**Comment by GregSutcliffe** [comment]
Thanks! I've added you and @lzap to repo with admin rights, and added @lzap to the rubygem.
