### ISSUE TITLE
send method collides with ruby's builtin Object.send

### ISSUE THREAD

**Issue by kepstin** [theforeman/journald-logger#7]
I've hit an issue where the journald-logger gem does not work as a drop-in replacement for Logger.

The delayed_job code calls the logger by running
```ruby
logger.send(level, "#{Time.now.strftime('%FT%T%z')}: #{text}")
```
where `level` is a symbol, like `:info`, `:debug` etc. It expects to be calling the ruby `Object.send` method, which will forward to the appropriate instance method `logger.info`, `logger.debug`, etc. depending on the log level.

However, `journald-logger` overrides the `send` method with a method that behaves completely differently, so this doesn't work.

(Note that the code using the `send` method can be changed to call `__send__` instead to work around this issue, but requiring code changes means it's not a drop-in replacement.)

**Comment by lzap** [comment]
Hello, thanks for the report. Let's move it to the PR which fixes it - can you review please?

https://github.com/theforeman/journald-logger/pull/8
